from . import test_attendance
from . import test_attendance_reverse_sync
from . import test_timesheet
from . import test_api
from . import test_idempotence
from . import test_record_rules
from . import test_workorder_mismatch
from . import test_compte_rendu
from . import test_pause_no_fake_departure
from . import test_sync_departure_guard
from . import test_recompute_attendance
from . import test_completion
from . import test_sync
