# Copyright 2026 Ocleaneo
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import api, fields, models


class OcleaneoMobilePointage(models.Model):
    _name = "ocleaneo.mobile.pointage"
    _description = "Mobile clocking log"
    _order = "datetime desc, id desc"

    # The idempotency key is enforced by the database, not by the search that
    # POST /api/mobile/pointage runs before creating: that search is a
    # check-then-act, so two retries arriving at once both find nothing and
    # both create a clocking. Postgres allows any number of NULLs in a unique
    # index, so clockings with no client_ref (backoffice entries, imports) are
    # unaffected. See the controller for how a losing insert is turned back
    # into the original response.
    _sql_constraints = [
        (
            "client_ref_uniq",
            "unique (user_id, client_ref)",
            "This clocking has already been recorded (duplicate client reference).",
        ),
    ]

    user_id = fields.Many2one("res.users", string="User", required=True, index=True)
    employee_id = fields.Many2one("hr.employee", string="Employee", index=True)
    fsm_order_id = fields.Many2one("fsm.order", string="FSM Order", index=True)
    fsm_location_id = fields.Many2one("fsm.location", string="FSM Location", index=True)

    type = fields.Selection([
        ("arrivee", "Arrivée"),
        ("depart", "Départ"),
        ("pause_debut", "Début de pause"),
        ("pause_fin", "Fin de pause"),
    ], string="Type", required=True)

    datetime = fields.Datetime(string="Date/Heure", required=True, default=fields.Datetime.now)
    gps_latitude = fields.Float(string="Latitude", digits=(10, 7))
    gps_longitude = fields.Float(string="Longitude", digits=(10, 7))
    gps_accuracy = fields.Float(string="GPS Accuracy (m)")
    nfc_tag_id = fields.Char(string="NFC Tag ID")
    client_ref = fields.Char(
        string="Client Reference",
        index=True,
        copy=False,
        help="Idempotency key generated by the mobile app for this clocking "
             "(see frontend CreateTimeEntryPayload.clientRef). Lets "
             "POST /api/mobile/pointage recognize a retried request — e.g. "
             "after an offline queue replay, or a response lost to a "
             "network drop right after the server processed it — and "
             "return the original record instead of creating a duplicate.",
    )
    # Attachable from the Odoo backoffice only. /api/mobile/pointage used to
    # accept a `photo` parameter that was never stored anywhere — an endpoint
    # silently discarding what a caller sends is worse than not accepting it,
    # so the parameter is gone. Wire it back to this field if the app ever
    # needs to upload one.
    photo_id = fields.Many2one("ir.attachment", string="Photo")
    commentaire = fields.Text(string="Commentaire")
    source = fields.Selection([
        ("mobile", "Mobile"),
        ("manuel", "Manuel"),
        ("import", "Import"),
    ], string="Source", default="mobile", required=True)

    state = fields.Selection([
        ("brouillon", "Brouillon"),
        ("valide", "Validé"),
        ("annule", "Annulé"),
    ], string="État", default="valide", required=True)

    company_id = fields.Many2one(
        "res.company",
        string="Company",
        required=True,
        default=lambda self: self.env.company,
    )

    hr_attendance_id = fields.Many2one("hr.attendance", string="Attendance record", readonly=True)
    timesheet_line_ids = fields.Many2many(
        "account.analytic.line",
        "ocleaneo_mobile_pointage_timesheet_rel",
        "pointage_id",
        "timesheet_id",
        string="Timesheet lines",
        readonly=True,
    )

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get("employee_id") and vals.get("user_id"):
                user = self.env["res.users"].sudo().browse(vals["user_id"])
                employee = user.get_employee_for_mobile()
                if employee:
                    vals["employee_id"] = employee.id
                    vals["company_id"] = employee.company_id.id or user.company_id.id
            if not vals.get("company_id") and vals.get("user_id"):
                user = self.env["res.users"].sudo().browse(vals["user_id"])
                vals["company_id"] = user.company_id.id
        return super(OcleaneoMobilePointage, self).create(vals_list)

    def action_valider(self):
        self.write({"state": "valide"})

    def action_annuler(self):
        self.write({"state": "annule"})
