# Copyright 2026 Ocleaneo
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

import re

from odoo import api, fields, models

_HEX_ONLY_RE = re.compile(r"[^0-9a-fA-F]")


def canonical_nfc_uid(value):
    """Normalize any spelling of a physical NFC UID to one canonical form:
    uppercase, colon-separated every 2 hex digits — e.g. "041779c9780000"
    and "04:17:79:C9:78:00:00" both become "04:17:79:C9:78:00:00".

    Mirrors formatNfcIdWithColons()/normalizeNfcId() in the mobile app
    (ocleaneo_mobile_app frontend/src/stores/pointage.ts), which strips
    everything but hex digits and lowercases before comparing a scanned
    UID against a chantier's — without a matching normalization here,
    uid_uniq below only catches a literal re-entry of the exact same
    string, not the same physical badge typed or scanned in a different
    case or with/without separators, and two registry entries for one
    badge is exactly the kind of "which one is real" confusion this
    registry exists to prevent.

    An empty/blank result normalizes to False, not "" — Postgres treats
    '' as a real value for uniqueness purposes (unlike NULL, which it
    allows any number of), so a field merely cleared in the form would
    otherwise collide with the next tag someone also leaves blank.
    """
    if not value:
        return False
    hex_only = _HEX_ONLY_RE.sub("", value).upper()
    if not hex_only:
        return False
    return ":".join(hex_only[i:i + 2] for i in range(0, len(hex_only), 2))


class OcleaneoNfcTag(models.Model):
    _name = "ocleaneo.nfc.tag"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _description = "NFC Tag Registry"
    _order = "name asc, id desc"

    name = fields.Char(
        string="Tag Number",
        required=True,
        index=True,
        readonly=True,
        default=lambda self: self.env["ir.sequence"].next_by_code("ocleaneo.nfc.tag"),
        help="Internal unique number generated by the registry.",
    )
    uid = fields.Char(
        string="Physical UID",
        index=True,
        help="Scanned NFC UID (e.g. 04:17:79:C9:78:00:00). Stored in one place only.",
    )
    location_id = fields.Many2one(
        "fsm.location",
        string="Location",
        index=True,
        tracking=True,
        help="The single field-service location this tag is assigned to.",
    )
    partner_id = fields.Many2one(
        "res.partner",
        string="Customer",
        related="location_id.partner_id",
        store=True,
        index=True,
        readonly=True,
        help="Customer inferred from the assigned location.",
    )
    state = fields.Selection([
        ("draft", "Draft"),
        ("active", "Active"),
        ("lost", "Lost"),
        ("disabled", "Disabled"),
    ], string="Status", default="draft", required=True, tracking=True)
    # The NFC chip reference, not a business classification — determines
    # what the badge can physically do (memory size, read range, whether
    # it supports NDEF) and drives which replacement stock to order. Kept
    # as a fixed Selection like `state` rather than an editable Many2one:
    # this is a stable list of chip models the company plausibly buys for
    # this use case (building/site access badges), not an open taxonomy
    # end users should be adding to from the UI — and deliberately not the
    # full NFC Forum catalogue (Type 1/Topaz, Type 3/FeliCa, Type 5/ICODE
    # never show up in this context and would only clutter the dropdown).
    tag_type = fields.Selection([
        # NFC Forum Type 2 (ISO/IEC 14443A) — NXP NTAG, the common cheap
        # sticker/keyfob family.
        ("ntag213", "NTAG213"),
        ("ntag215", "NTAG215"),
        ("ntag216", "NTAG216"),
        ("ntag213f", "NTAG213F (détection de champ)"),
        ("ntag216f", "NTAG216F (détection de champ)"),
        # NFC Forum Type 4 (ISO/IEC 14443A) — authenticated, anti-clonage.
        ("ntag424_dna", "NTAG424 DNA (authentification)"),
        # Mifare Classic (ISO/IEC 14443A + Crypto1 propriétaire, hors norme
        # NFC Forum) — très répandu sur le contrôle d'accès bâtiment.
        ("mifare_classic_1k", "Mifare Classic 1K"),
        ("mifare_classic_4k", "Mifare Classic 4K"),
        ("mifare_plus", "Mifare Plus"),
        # Mifare Ultralight (NFC Forum Type 2).
        ("mifare_ultralight", "Mifare Ultralight"),
        ("mifare_ultralight_c", "Mifare Ultralight C"),
        ("mifare_ultralight_ev1", "Mifare Ultralight EV1"),
        # Mifare DESFire (NFC Forum Type 4) — authentification forte.
        ("mifare_desfire_ev1", "Mifare DESFire EV1"),
        ("mifare_desfire_ev2", "Mifare DESFire EV2"),
        ("mifare_desfire_ev3", "Mifare DESFire EV3"),
        ("other", "Autre"),
    ], string="Tag Type", tracking=True)
    note = fields.Text(string="Note")
    company_id = fields.Many2one(
        "res.company",
        string="Company",
        default=lambda self: self.env.company,
        required=True,
        index=True,
    )
    active = fields.Boolean(default=True)

    _sql_constraints = [
        ("name_uniq", "unique (name)", "The tag number must be unique."),
        ("uid_uniq", "unique (uid)", "The physical NFC UID must be unique."),
        (
            "location_uniq",
            "unique (location_id)",
            "A location can only have one NFC tag assigned.",
        ),
    ]

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if "uid" in vals:
                vals["uid"] = canonical_nfc_uid(vals["uid"])
        return super().create(vals_list)

    def write(self, vals):
        if "uid" in vals:
            vals = dict(vals, uid=canonical_nfc_uid(vals["uid"]))
        return super().write(vals)

    def action_activate(self):
        self.write({"state": "active"})

    def action_disable(self):
        self.write({"state": "disabled"})

    def action_mark_lost(self):
        self.write({"state": "lost"})

    def name_get(self):
        return [(tag.id, f"{tag.name} ({tag.uid or 'no UID'})") for tag in self]
